[package]
name = "xorsum"
version = "2.0.1"
edition = "2021"
description = "Get XOR hash/digest with this command-line tool"
keywords = ["checksum", "checksums", "hash", "hashes", "hasher", "digest", "xor", "file", "files", "data", "binary", "hexadecimal"]
categories = ["command-line-utilities", "algorithms"]
license = "Unlicense"
repository = "https://github.com/Rudxain/xorsum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
