[package]
name = "xorsum"
version = "3.0.0"
edition = "2021"
description = "Get XOR hash/digest with this command-line tool"
keywords = ["checksum", "checksums", "hash", "hashes", "hasher", "digest", "xor", "file", "files", "data", "binary", "hexadecimal"]
categories = ["command-line-utilities", "algorithms"]
license = "Unlicense"
repository = "https://github.com/Rudxain/xorsum"

[dependencies]