[package]
name = "xorsum"
version = "0.0.1"
edition = "2021"
description = "Get XOR hash/digest of a file with this command-line utility"
keywords = ["checksum", "hash", "xor"]
categories = ["command-line-utilities", "algorithms"]
license = "Unlicense"
repository = "https://github.com/Rudxain/xorsum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
